name: MongoDB’ye Otomatik Aktarım
on:
  push:                        # Her push'ta tetiklenir
    branches: [ main ]
jobs:
  aktarim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: pymongo kur
        run: pip install pymongo
      - name: Verileri MongoDB Atlas'a aktar
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: python otomatik_aktar.py